[env:rpi3bplus_rfm95_oled]
extends = portduino_base
board = cross_platform

build_flags = ${portduino_base.build_flags} -O0 -I variants/rpi3bplus_rfm95_oled
  -DMESHTASTIC_DS18B20_TEMP_ONLY=1
  -DUSERPREFS_CONFIG_DISPLAY_SCREEN_ON_SECS=0

lib_deps = ${portduino_base.lib_deps}
build_src_filter = ${portduino_base.build_src_filter} +<../variants/rpi3bplus_rfm95_oled> +<modules/Telemetry/EnvironmentTelemetry.cpp> +<modules/Telemetry/Sensor/>
