[env:native]
extends = portduino_base
; The pkg-config commands below optionally add link flags.
; the || : is just a "or run the null command" to avoid returning an error code
build_flags = ${portduino_base.build_flags} -O0 -I variants/portduino
  -I /usr/include
  !pkg-config --libs libulfius --silence-errors || :
  !pkg-config --libs openssl --silence-errors || :
board = cross_platform
lib_deps = ${portduino_base.lib_deps}
build_src_filter = ${portduino_base.build_src_filter}

[env:rpi3bplus_rfm95_oled]
extends = portduino_base
board = cross_platform
build_flags = ${portduino_base.build_flags} -O0
  -I variants/rpi3bplus_rfm95_oled
  -I /usr/include
  !pkg-config --libs libulfius --silence-errors || :
  !pkg-config --libs openssl --silence-errors || :
  -DMESHTASTIC_DS18B20_TEMP_ONLY=1
  -DUSERPREFS_CONFIG_DISPLAY_SCREEN_ON_SECS=0
lib_deps = ${portduino_base.lib_deps}
build_src_filter = ${portduino_base.build_src_filter}
  -<../variants/portduino>
  +<../variants/rpi3bplus_rfm95_oled>
  +<modules/Telemetry/EnvironmentTelemetry.cpp>
  +<modules/Telemetry/Sensor/DS18B20Sensor.cpp>
